apiVersion: v1 # Versão da api
kind: Service ## tipo de serviço
metadata: ## dados que caracterizam o serviço
  name: nginx-service
spec: ## especificação do serviço
  type: LoadBalancer ## Tipo de serviço [ClusterIp,NodePort, LoadBalancer]
  selector: ## Pega o deployment que possue essa label
    app: nginx
  ports: 
  - name: nginx-port
    port: 80 ## Porta que vai ser exposta 
    targetPort: 80 ## porta do container
  # - name: nginx-other
  #   port: 3000
  #   targetPort: 80