apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-slackbot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slackbot-role
rules:
  - apiGroups: ["v1"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: slackbot-role-binding
subjects:
- kind: ServiceAccount
  name: user-slackbot
roleRef:
  kind: ClusterRole
  name: slackbot-role
  apiGroup: rbac.authorization.k8s.io



  # kubectl create clusterrolebinding serviceaccounts-cluster-admin \
  # --clusterrole=cluster-admin \
  # --group=system:serviceaccounts

#   kubectl create clusterrolebinding dashboard-admin-sa 
# --clusterrole=cluster-admin --serviceaccount=default:dashboard-admin-sa